INSERT INTO COORDINACION VALUES ('09-10020','Coordinacion de Administración de Email');
INSERT INTO COORDINACION VALUES ('C-0001','Coordinacion de Administracion de Turismo y Hoteleria');
INSERT INTO COORDINACION VALUES ('C-0002','Coordinacion de Alimentos');
INSERT INTO COORDINACION VALUES ('C-0003','Coordinacion de Arquitectura');
INSERT INTO COORDINACION VALUES ('C-0004','Coordinacion de Biologia');
INSERT INTO COORDINACION VALUES ('C-0005','Coordinacion de Ciencias Aplicadas e Ingenieria');
INSERT INTO COORDINACION VALUES ('C-0006','Coordinacion de Ciencias Aplicadas (Litoral)');
INSERT INTO COORDINACION VALUES ('C-0007','Coordinacion de Ciencias de los Alimentos');
INSERT INTO COORDINACION VALUES ('C-0008','Coordinacion de Ciencias Politicas');
INSERT INTO COORDINACION VALUES ('C-0009','Coordinacion de Cursos en Cooperacion');
INSERT INTO COORDINACION VALUES ('C-0010','Coordinacion de Desarrollo del Ambiente');
INSERT INTO COORDINACION VALUES ('C-0011','Coordinacion de Doctorado en Ingenieria');
INSERT INTO COORDINACION VALUES ('C-0012','Coordinacion de Extension Universitaria');
INSERT INTO COORDINACION VALUES ('C-0013','Coordinacion de Extension Universitaria (Litoral)');
INSERT INTO COORDINACION VALUES ('C-0014','Coordinacion de Filosofia');
INSERT INTO COORDINACION VALUES ('C-0015','Coordinacion de Fisica');
INSERT INTO COORDINACION VALUES ('C-0016','Coordinacion de Gerencia de Empresas');
INSERT INTO COORDINACION VALUES ('C-0017','Coordinacion de Ingenieria de Computacion');
INSERT INTO COORDINACION VALUES ('C-0018','Coordinacion de Ingenieria de Materiales');
INSERT INTO COORDINACION VALUES ('C-0019','Coordinacion de Ingenieria de Produccion');
INSERT INTO COORDINACION VALUES ('C-0020','Coordinacion de Ingenieria de Sistemas');
INSERT INTO COORDINACION VALUES ('C-0021','Coordinacion de Ingenieria Electrica');
INSERT INTO COORDINACION VALUES ('C-0022','Coordinacion de Ingenieria Electronica');
INSERT INTO COORDINACION VALUES ('C-0023','Coordinacion de Ingenieria Geofisica');
INSERT INTO COORDINACION VALUES ('C-0024','Coordinacion de Ingenieria Mecanica');
INSERT INTO COORDINACION VALUES ('C-0025','Coordinacion de Ingenieria Quimica');
INSERT INTO COORDINACION VALUES ('C-0026','Coordinacion de Licenciatura en Quimica');
INSERT INTO COORDINACION VALUES ('C-0027','Coordinacion de Linguistica Aplicada');
INSERT INTO COORDINACION VALUES ('C-0028','Coordinacion de Literatura Latinoamericana');
INSERT INTO COORDINACION VALUES ('C-0029','Coordinacion del Nucleo');
INSERT INTO COORDINACION VALUES ('C-0030','Coordinacion de Matematicas');
INSERT INTO COORDINACION VALUES ('C-0031','Coordinacion de Planificacion e Ingenieria de Recursos Hidraulicos');
INSERT INTO COORDINACION VALUES ('C-0032','Coordinacion de Postgrado en Ciencias Biologicas');
INSERT INTO COORDINACION VALUES ('C-0033','Coordinacion de Postgrado en Ciencias de los Alimentos y Nutricion');
INSERT INTO COORDINACION VALUES ('C-0034','Coordinacion de Postgrado en Ciencias Politicas');
INSERT INTO COORDINACION VALUES ('C-0035','Coordinacion de Postgrado en Desarrollo y Ambiente');
INSERT INTO COORDINACION VALUES ('C-0036','Coordinacion de Postgrado en Educacion');
INSERT INTO COORDINACION VALUES ('C-0037','Coordinacion de Postgrado en Estadistica');
INSERT INTO COORDINACION VALUES ('C-0038','Coordinacion de Postgrado en Filosofia');
INSERT INTO COORDINACION VALUES ('C-0039','Coordinacion de Postgrado en Ingenieria de Materiales');
INSERT INTO COORDINACION VALUES ('C-0040','Coordinacion de Postgrado en Ingenieria de Sistemas');
INSERT INTO COORDINACION VALUES ('C-0041','Coordinacion de Postgrado en Ingenieria Electrica');
INSERT INTO COORDINACION VALUES ('C-0042','Coordinacion de Postgrado en Ingenieria Electronica');
INSERT INTO COORDINACION VALUES ('C-0043','Coordinacion de Postgrado en Ingenieria Empresarial');
INSERT INTO COORDINACION VALUES ('C-0044','Coordinacion de Postgrado en Ingenieria Mecanica');
INSERT INTO COORDINACION VALUES ('C-0045','Coordinacion de Postgrado en Ingenieria Quimica');
INSERT INTO COORDINACION VALUES ('C-0046','Coordinacion de Postgrado en Literatura');
INSERT INTO COORDINACION VALUES ('C-0047','Coordinacion de Postgrado en Musica');
INSERT INTO COORDINACION VALUES ('C-0048','Coordinacion de Postgrado (Litoral)');
INSERT INTO COORDINACION VALUES ('C-0049','Coordinacion de Psicologia');
INSERT INTO COORDINACION VALUES ('C-0050','Coordinacion de Relaciones con la Comunidad');
INSERT INTO COORDINACION VALUES ('C-0051','Coordinacion de Transporte Urbano');
INSERT INTO COORDINACION VALUES ('C-0052','Coordinacion de Urbanismo');