INSERT INTO DEPARTAMENTO VALUES ('09-10219','Departamento de pruebas de Email');
INSERT INTO DEPARTAMENTO VALUES ('D-2001','Departamento de Administracion de Personal');
INSERT INTO DEPARTAMENTO VALUES ('D-2002','Departamento de Administracion y Almacen');
INSERT INTO DEPARTAMENTO VALUES ('D-2003','Departamento de Admision y Control de Estudios');
INSERT INTO DEPARTAMENTO VALUES ('D-2004','Departamento de Admision y Control de Estudios (Litoral)');
INSERT INTO DEPARTAMENTO VALUES ('D-2005','Departamento de Adquisicion y Reproduccion');
INSERT INTO DEPARTAMENTO VALUES ('D-2006','Departamento de Adquisicion y Reproduccion (Litoral)');
INSERT INTO DEPARTAMENTO VALUES ('D-2007','Departamento de Archivo y Estadistica (Litoral)');
INSERT INTO DEPARTAMENTO VALUES ('D-2008','Departamento de Atencion al Usuario');
INSERT INTO DEPARTAMENTO VALUES ('D-2009','Departamento de Bienes Nacionales');
INSERT INTO DEPARTAMENTO VALUES ('D-2010','Departamento de Bioingenieria');
INSERT INTO DEPARTAMENTO VALUES ('D-2011','Departamento de Biologia Celular');
INSERT INTO DEPARTAMENTO VALUES ('D-2012','Departamento de Biologia Celular y Organismos');
INSERT INTO DEPARTAMENTO VALUES ('D-2013','Departamento de Biologia de Organismos');
INSERT INTO DEPARTAMENTO VALUES ('D-2014','Departamento de Ciencias de la Tierra');
INSERT INTO DEPARTAMENTO VALUES ('D-2015','Departamento de Ciencias de los Materiales');
INSERT INTO DEPARTAMENTO VALUES ('D-2016','Departamento de Ciencias Economicas y Administrativas');
INSERT INTO DEPARTAMENTO VALUES ('D-2017','Departamento de Ciencias Politicas');
INSERT INTO DEPARTAMENTO VALUES ('D-2018','Departamento de Ciencias Sociales');
INSERT INTO DEPARTAMENTO VALUES ('D-2019','Departamento de Ciencia y Tecnologia del Comportamiento');
INSERT INTO DEPARTAMENTO VALUES ('D-2020','Departamento de Compras y Suministros');
INSERT INTO DEPARTAMENTO VALUES ('D-2021','Departamento de Computacion (Litoral)');
INSERT INTO DEPARTAMENTO VALUES ('D-2022','Departamento de Computacion y Tecnologia de la Informacion');
INSERT INTO DEPARTAMENTO VALUES ('D-2023','Departamento de Computo Cientifico y Estadistica');
INSERT INTO DEPARTAMENTO VALUES ('D-2024','Departamento de Contabilidad');
INSERT INTO DEPARTAMENTO VALUES ('D-2025','Departamento de Conversion y Transporte de Energia');
INSERT INTO DEPARTAMENTO VALUES ('D-2026','Departamento de Correspondencia');
INSERT INTO DEPARTAMENTO VALUES ('D-2027','Departamento de Desarrollo de Personal');
INSERT INTO DEPARTAMENTO VALUES ('D-2028','Departamento de Diseño Arquitectura y Artes Plasticas');
INSERT INTO DEPARTAMENTO VALUES ('D-2029','Departamento de Ejecucion');
INSERT INTO DEPARTAMENTO VALUES ('D-2030','Departamento de Electronica y Circuitos');
INSERT INTO DEPARTAMENTO VALUES ('D-2031','Departamento de Estudios Ambientales');
INSERT INTO DEPARTAMENTO VALUES ('D-2032','Departamento de Filosofia');
INSERT INTO DEPARTAMENTO VALUES ('D-2033','Departamento de Finanzas');
INSERT INTO DEPARTAMENTO VALUES ('D-2034','Departamento de Finanzas (Litoral)');
INSERT INTO DEPARTAMENTO VALUES ('D-2035','Departamento de Fisica');
INSERT INTO DEPARTAMENTO VALUES ('D-2036','Departamento de Formacion General (Litoral)');
INSERT INTO DEPARTAMENTO VALUES ('D-2037','Departamento de Formacion General y Ciencias Basicas');
INSERT INTO DEPARTAMENTO VALUES ('D-2038','Departamento de Gestion del Capital Humano');
INSERT INTO DEPARTAMENTO VALUES ('D-2039','Departamento de Idiomas');
INSERT INTO DEPARTAMENTO VALUES ('D-2040','Departamento de Informacion y Documentacion');
INSERT INTO DEPARTAMENTO VALUES ('D-2041','Departamento de Informacion y Medios');
INSERT INTO DEPARTAMENTO VALUES ('D-2042','Departamento de Ingenieria Electrica');
INSERT INTO DEPARTAMENTO VALUES ('D-2043','Departamento de Ingenieria y Mantenimiento');
INSERT INTO DEPARTAMENTO VALUES ('D-2044','Departamento de Ingenieria y Mantenimiento (Litoral)');
INSERT INTO DEPARTAMENTO VALUES ('D-2045','Departamento de Lengua y Literatura');
INSERT INTO DEPARTAMENTO VALUES ('D-2046','Departamento de Matematicas Puras y Aplicadas');
INSERT INTO DEPARTAMENTO VALUES ('D-2047','Departamento de Mecanica');
INSERT INTO DEPARTAMENTO VALUES ('D-2048','Departamento de Musica');
INSERT INTO DEPARTAMENTO VALUES ('D-2049','Departamento de Planificacion Urbana');
INSERT INTO DEPARTAMENTO VALUES ('D-2050','Departamento de Planta Fisica');
INSERT INTO DEPARTAMENTO VALUES ('D-2051','Departamento de Procesos Biologicos y Bioquimicos');
INSERT INTO DEPARTAMENTO VALUES ('D-2052','Departamento de Procesos y Sistemas');
INSERT INTO DEPARTAMENTO VALUES ('D-2053','Departamento de Produccion de Impresos');
INSERT INTO DEPARTAMENTO VALUES ('D-2054','Departamento de Quimica y Procesos');
INSERT INTO DEPARTAMENTO VALUES ('D-2055','Departamento de Recursos Humanos');
INSERT INTO DEPARTAMENTO VALUES ('D-2056','Departamento de Recursos Humanos (Litoral)');
INSERT INTO DEPARTAMENTO VALUES ('D-2057','Departamento de Redes');
INSERT INTO DEPARTAMENTO VALUES ('D-2058','Departamento de Registro y Control Administrativo');
INSERT INTO DEPARTAMENTO VALUES ('D-2059','Departamento de Registro y Control Financiero');
INSERT INTO DEPARTAMENTO VALUES ('D-2060','Departamento de Relaciones Laborales');
INSERT INTO DEPARTAMENTO VALUES ('D-2061','Departamento de Seguridad y Servicios');
INSERT INTO DEPARTAMENTO VALUES ('D-2062','Departamento de Servicios Audiovisuales');
INSERT INTO DEPARTAMENTO VALUES ('D-2063','Departamento de Servicios de Red');
INSERT INTO DEPARTAMENTO VALUES ('D-2064','Departamento de Servicios Generales');
INSERT INTO DEPARTAMENTO VALUES ('D-2065','Departamento de Servicios Telefonicos');
INSERT INTO DEPARTAMENTO VALUES ('D-2066','Departamento de Servicos Generales');
INSERT INTO DEPARTAMENTO VALUES ('D-2067','Departamento de Soporte de Operaciones y Sistemas');
INSERT INTO DEPARTAMENTO VALUES ('D-2068','Departamento de Tecnologia de Procesos Biologicos y Bioquimicos');
INSERT INTO DEPARTAMENTO VALUES ('D-2069','Departamento de Tecnologia de Servicios');
INSERT INTO DEPARTAMENTO VALUES ('D-2070','Departamento de Tecnologia Industrial');
INSERT INTO DEPARTAMENTO VALUES ('D-2071','Departamento de Tecnologia Informatica');
INSERT INTO DEPARTAMENTO VALUES ('D-2072','Departamento de Termodinamica y Fenomenos de Transferencia');
INSERT INTO DEPARTAMENTO VALUES ('D-2073','Departamento de Tesoreria');
INSERT INTO DEPARTAMENTO VALUES ('D-2074','Departamento de Urbanismo');